name: ZMK Firmware

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  convert-and-store-keymap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python scripts/convert_keymap.py -c q2c --in-path "$GITHUB_WORKSPACE/config/charybdis.keymap"

      - uses: actions/upload-artifact@v4
        with:
          name: keymap_files
          path: ${{ github.workspace }}/config/*.keymap

  build:
    needs: convert-and-store-keymap
    uses: ./.github/workflows/user_config_build.yaml
    # uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  keymap_images:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/draw_keymaps.yaml
    # credit to https://github.com/caksoylar/keymap-drawer

  release:
    needs: [build, keymap_images]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware
          merge-multiple: true

      - name: Release Firmware
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
          name: ${{ github.ref_type == 'tag' && github.ref_name || 'Latest Firmware' }}
          files: |
            firmware/*.uf2
            firmware/*.bin

